name: Build LaTeX Document

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-bibtex-extra texlive-science texlive-pictures texlive-electronics biber

    - name: Build PDF
      run: |
        make all

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf-document
        path: mainTemplatePDF.pdf
